// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1) {
  return window['go']['server']['App']['CreateTodo'](arg1);
}

export function CreateTodoGroup(arg1) {
  return window['go']['server']['App']['CreateTodoGroup'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['server']['App']['DeleteTodo'](arg1);
}

export function DeleteTodoGroup(arg1) {
  return window['go']['server']['App']['DeleteTodoGroup'](arg1);
}

export function GetAllTodoGroups(arg1) {
  return window['go']['server']['App']['GetAllTodoGroups'](arg1);
}

export function GetTodo(arg1) {
  return window['go']['server']['App']['GetTodo'](arg1);
}

export function GetTodoGroup(arg1) {
  return window['go']['server']['App']['GetTodoGroup'](arg1);
}

export function GetTodoList(arg1) {
  return window['go']['server']['App']['GetTodoList'](arg1);
}

export function UpdateTodo(arg1) {
  return window['go']['server']['App']['UpdateTodo'](arg1);
}

export function UpdateTodoGroup(arg1) {
  return window['go']['server']['App']['UpdateTodoGroup'](arg1);
}

export function UpdateTodoState(arg1) {
  return window['go']['server']['App']['UpdateTodoState'](arg1);
}
