// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateTodo(arg1:db.Todo):Promise<void>;

export function CreateTodoGroup(arg1:db.TodoGroup):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function DeleteTodoGroup(arg1:number):Promise<void>;

export function GetAllTodoGroups(arg1:string):Promise<Array<db.TodoGroup>>;

export function GetTodo(arg1:number):Promise<db.Todo>;

export function GetTodoGroup(arg1:number):Promise<db.TodoGroup>;

export function GetTodoList(arg1:db.QryTodoList):Promise<db.TodoList>;

export function UpdateTodo(arg1:db.Todo):Promise<void>;

export function UpdateTodoGroup(arg1:db.TodoGroup):Promise<void>;

export function UpdateTodoState(arg1:number):Promise<void>;
