// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTodo'](arg1, arg2, arg3);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetAllTodos(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAllTodos'](arg1, arg2, arg3);
}

export function GetTodo(arg1) {
  return window['go']['main']['App']['GetTodo'](arg1);
}

export function UpdateTodo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2, arg3, arg4, arg5);
}
