// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateTodo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetAllTodos(arg1:string,arg2:string,arg3:number):Promise<Array<db.Todo>>;

export function GetTodo(arg1:number):Promise<db.Todo>;

export function UpdateTodo(arg1:number,arg2:string,arg3:string,arg4:boolean,arg5:string):Promise<void>;
