// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateTodo(arg1:string,arg2:string):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetAllTodos():Promise<Array<db.Todo>>;

export function GetTodo(arg1:number):Promise<db.Todo>;

export function Greet(arg1:string):Promise<string>;

export function UpdateTodo(arg1:number,arg2:string,arg3:boolean,arg4:string):Promise<void>;
